//--------------------------------------------------------------------------------
// Auto-generated by LiteX (58322a1d2) on 2026-10-01 23:03:29
//--------------------------------------------------------------------------------
#ifndef __GENERATED_MEM_H
#define __GENERATED_MEM_H

#ifndef ROM_BASE
#define ROM_BASE 0x00000000L
#define ROM_BASE_VA 0x00000000L
#define ROM_SIZE 0x00008000
#endif

#ifndef SRAM_BASE
#define SRAM_BASE 0x10000000L
#define SRAM_BASE_VA 0x10000000L
#define SRAM_SIZE 0x00002000
#endif

#ifndef MAIN_RAM_BASE
#define MAIN_RAM_BASE 0x40000000L
#define MAIN_RAM_BASE_VA 0x40000000L
#define MAIN_RAM_SIZE 0x08000000
#endif

#ifndef DDR_DIAGNOSTIC_RAM_BASE
#define DDR_DIAGNOSTIC_RAM_BASE 0x20000000L
#define DDR_DIAGNOSTIC_RAM_BASE_VA 0x20000000L
#define DDR_DIAGNOSTIC_RAM_SIZE 0x00004000
#endif

#ifndef DDR_UNCACHED_BASE
#define DDR_UNCACHED_BASE 0xc0000000L
#define DDR_UNCACHED_BASE_VA 0xc0000000L
#define DDR_UNCACHED_SIZE 0x08000000
#endif

#ifndef CSR_BASE
#define CSR_BASE 0xf0000000L
#define CSR_BASE_VA 0xf0000000L
#define CSR_SIZE 0x00010000
#endif

#ifndef MEM_REGIONS
#define MEM_REGIONS "ROM                 0x00000000 0x8000 \nSRAM                0x10000000 0x2000 \nMAIN_RAM            0x40000000 0x8000000 \nDDR_DIAGNOSTIC_RAM  0x20000000 0x4000 \nDDR_UNCACHED        0xc0000000 0x8000000 \nCSR                 0xf0000000 0x10000 "
#endif

#ifndef MEM_REGIONS_DETAILS
#define MEM_REGIONS_DETAILS "Region             Origin     End        Size \nROM                0x00000000 0x00007fff 0x8000 \nSRAM               0x10000000 0x10001fff 0x2000 \nMAIN_RAM           0x40000000 0x47ffffff 0x8000000 \nDDR_DIAGNOSTIC_RAM 0x20000000 0x20003fff 0x4000 \nDDR_UNCACHED       0xc0000000 0xc7ffffff 0x8000000 \nCSR                0xf0000000 0xf000ffff 0x10000 "
#endif
#endif
