//--------------------------------------------------------------------------------
// Auto-generated by LiteX (58322a1d2) on 2026-10-01 23:03:29
//--------------------------------------------------------------------------------
#ifndef __GENERATED_SOC_H
#define __GENERATED_SOC_H
#include <stdint.h>
#define CONFIG_PLATFORM_NAME "sipeed_tang_primer_20k"
#define CONFIG_CLOCK_FREQUENCY 0x2dc6c00
#define CONFIG_CPU_HAS_INTERRUPT
#define CONFIG_CPU_RESET_ADDR 0
#define CONFIG_CPU_TYPE_VEXRISCV
#define CONFIG_CPU_VARIANT_MINIMAL
#define CONFIG_CPU_FAMILY "riscv"
#define CONFIG_CPU_NAME "vexriscv"
#define CONFIG_CPU_HUMAN_NAME "VexRiscv_Min"
#define CONFIG_CPU_NOP "nop"
#define CONFIG_BIOS_NO_BUILD_TIME
#define CONFIG_IDENTIFIER "LiteX SoC on Tang Primer 20K"
#define CONFIG_L2_SIZE 0x2000
#define PROJECT_DDR_BYTES 0x8000000
#define PROJECT_DDR_PART "H5TQ1G63EFR"
#define PROJECT_DDR_ADDRESS_BITS 27
#define PROJECT_DDR_UNCACHED_BASE 0xc0000000
#define PROJECT_DDR_DIAGNOSTIC_BASE 0x20000000
#define PROJECT_DDR_L2_BYTES 0x2000
#define PROJECT_PROFILE "minimal"
#define PROJECT_MEMORY_MODE "ddr3"
#define PROJECT_GPIO_LED_COUNT 6
#define PROJECT_GPIO_BUTTON_COUNT 4
#define CONFIG_CSR_DATA_WIDTH 32
#define CONFIG_CSR_ALIGNMENT 32
#define CONFIG_CSR_ORDERING_BIG
#define CONFIG_BUS_STANDARD "wishbone"
#define CONFIG_BUS_DATA_WIDTH 32
#define CONFIG_BUS_ADDRESS_WIDTH 32
#define CONFIG_BUS_BURSTING 0
#define CONFIG_CPU_INTERRUPTS 2
#define TIMER0_INTERRUPT 1
#define UART_INTERRUPT 0

#ifndef __ASSEMBLER__
static inline const char * config_platform_name_read(void) {
	return "sipeed_tang_primer_20k";
}
static inline uint32_t config_clock_frequency_read(void) {
	return 0x2dc6c00;
}
static inline uint32_t config_cpu_reset_addr_read(void) {
	return 0;
}
static inline const char * config_cpu_family_read(void) {
	return "riscv";
}
static inline const char * config_cpu_name_read(void) {
	return "vexriscv";
}
static inline const char * config_cpu_human_name_read(void) {
	return "VexRiscv_Min";
}
static inline const char * config_cpu_nop_read(void) {
	return "nop";
}
static inline const char * config_identifier_read(void) {
	return "LiteX SoC on Tang Primer 20K";
}
static inline uint32_t config_l2_size_read(void) {
	return 0x2000;
}
static inline uint32_t project_ddr_bytes_read(void) {
	return 0x8000000;
}
static inline const char * project_ddr_part_read(void) {
	return "H5TQ1G63EFR";
}
static inline uint32_t project_ddr_address_bits_read(void) {
	return 27;
}
static inline uint32_t project_ddr_uncached_base_read(void) {
	return 0xc0000000;
}
static inline uint32_t project_ddr_diagnostic_base_read(void) {
	return 0x20000000;
}
static inline uint32_t project_ddr_l2_bytes_read(void) {
	return 0x2000;
}
static inline const char * project_profile_read(void) {
	return "minimal";
}
static inline const char * project_memory_mode_read(void) {
	return "ddr3";
}
static inline uint32_t project_gpio_led_count_read(void) {
	return 6;
}
static inline uint32_t project_gpio_button_count_read(void) {
	return 4;
}
static inline uint32_t config_csr_data_width_read(void) {
	return 32;
}
static inline uint32_t config_csr_alignment_read(void) {
	return 32;
}
static inline const char * config_bus_standard_read(void) {
	return "wishbone";
}
static inline uint32_t config_bus_data_width_read(void) {
	return 32;
}
static inline uint32_t config_bus_address_width_read(void) {
	return 32;
}
static inline uint32_t config_bus_bursting_read(void) {
	return 0;
}
static inline uint32_t config_cpu_interrupts_read(void) {
	return 2;
}
static inline uint32_t timer0_interrupt_read(void) {
	return 1;
}
static inline uint32_t uart_interrupt_read(void) {
	return 0;
}
#endif // !__ASSEMBLER__

#endif
