"""Physical memory fitted to the user's Tang Primer 20K board."""

DDR_PART = "H5TQ1G63EFR"
DDR_ROW_BITS = 13
DDR_BANK_BITS = 3
DDR_COLUMN_BITS = 10
DDR_DATA_BITS = 16
DDR_SIZE_BYTES = (1 << (DDR_ROW_BITS + DDR_BANK_BITS + DDR_COLUMN_BITS)) * (DDR_DATA_BITS // 8)
DDR_ADDRESS_BITS = DDR_SIZE_BYTES.bit_length() - 1
DDR_ALIAS_OFFSETS = DDR_ADDRESS_BITS - 2
DDR_VISIBILITY_SAMPLES = 64
DDR_VISIBILITY_STRIDE = DDR_SIZE_BYTES // DDR_VISIBILITY_SAMPLES
